repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.7.0'
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
        -   eslint@8.7.0
        -   eslint-config-google@0.14.0
        -   eslint-config-prettier@8.3.0
        -   eslint-plugin-prettier@4.0.0
        -   prettier@2.5.1
